otopark_otomasyonu/Controllers/AracController.cs
using otopark_otomasyonu.Models.Siniflar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace otopark_otomasyonu.Controllers
{
    public class AracController : Controller
    {
        OtoparkDbContext db = new OtoparkDbContext();
        // GET: Arac
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AracGoster()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AracGoster(Arac_bilgisi P)
        {
            db.Arac_bilgisis.Add(P);
            db.SaveChanges();
            return RedirectToAction("AracCikis");
        }

        public ActionResult AracCikis()
        {
            var listee = db.Arac_bilgisis.ToList();
            return View(listee);
        }

        public ActionResult SIL(int id)
        {
            db.Arac_bilgisis.Remove(db.Arac_bilgisis.Find(id));
            db.SaveChanges();
            return RedirectToAction("AracCikis");

        }

        public ActionResult AracGetir(int id)
        {
            var arac = db.Arac_bilgisis.Find(id);
            return View("AracGetir", arac);
        }

        public ActionResult AracıGuncelle(Arac_bilgisi P1)
        {
            var kisi = db.Arac_bilgisis.Find(P1.Arac_ID);
            kisi.Plaka = P1.Plaka;
            kisi.Marka = P1.Marka;
            kisi.Renk = P1.Renk;
            kisi.Kisi_ID = P1.Kisi_ID;
            db.SaveChanges();
            return RedirectToAction("AracCikis");
        }
    }
}

otopark_otomasyonu/Views/Arac/AracCikis.cshtml
@using otopark_otomasyonu.Models.Siniflar
@model List<Arac_bilgisi>
@{
    ViewBag.Title = "AracCikis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Section 1 Bitiş-->
<div class="container">
    <div class="row">
        <div class="col m12 s12">
            <h4>Otopark Araç Sil / Güncelle</h4>
            <table class="highlight responsive-table">
                <thead>
                    <tr>
                        <th>Aracın Numarası (ID)</th>
                        <th>Araç Sahibi (ID)</th>
                        <th>Aracın Sahibi Ad Soyad</th>
                        <th>Aracın Sahibi Telefon</th>
                        <th>Aracın Markası (ID)</th>
                        <th>Plaka</th>
                        <th>Yıl</th>
                        <th>Aracın Rengi</th>
                        <th>Araç Park Yeri (ID)</th>
                        <th>Giriş Tarihi</th>
                        
                    </tr>
                </thead>

                <tbody>
                    @foreach (var itemm in Model)
                    {
                        <tr>
                            <td>@itemm.Arac_ID -</td>
                            <td>@itemm.Kisi_ID</td>
                            <td>@itemm.Ad_soyad</td>
                            <td>@itemm.Telefon</td>
                            <td>@itemm.Marka_ID </td>
                            <td>@itemm.Plaka </td>
                            <td>@itemm.Yil </td>
                            <td>@itemm.Renk </td>
                            <td>@itemm.Py_ID </td>
                            <td>@itemm.Giris_Tarihi </td>
                            <td><a href="/Arac/AracGetir/@itemm.Arac_ID" class="waves-effect waves-light btn">Güncelle</a></td>
                            <td><a href="/Arac/SIL/@itemm.Arac_ID" class="waves-effect waves-light btn red darken-2">Araç Sil</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<br />
<br />
<br />
<!-- Section 1 Bitiş-->

otopark_otomasyonu/Views/Arac/AracGetir.cshtml
@model otopark_otomasyonu.Models.Siniflar.Arac_bilgisi
@{
    ViewBag.Title = "AracGetir";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col m12">
            <h4 class="center">Araç Bilgilerini Güncelle</h4>
            <p class="center light">Verilerinizi Güncelleyebilirsiniz.</p>
            <hr />
            @using (Html.BeginForm("AracıGuncelle", "Arac", FormMethod.Post))
            {
                @Html.TextBoxFor(m => m.Arac_ID, new { @class = "validate hide" })
                @Html.TextBoxFor(m => m.Kisi_ID, new { @class = "validate hide" })
                <div class="input-field col s6">
                    @Html.TextBoxFor(m => m.Ad_soyad, new { @class = "validate" })
                    <label for="Ad_soyad">Ad Soyad</label>
                </div>
                <div class="input-field col s6">
                    @Html.TextBoxFor(m => m.Telefon, new { @class = "validate" })
                    <label for="Telefon">Telefon</label>
                </div>
                @Html.TextBoxFor(m => m.Marka_ID, new { @class = "validate hide" })
        <div class="row">
            <div class="input-field col s6">
                <i class="material-icons prefix">account_circle</i>
                @Html.TextBoxFor(m => m.Plaka, new { @class = "validate" })
                <label for="Plaka">Plaka</label>
            </div>
            <div class="input-field col s6">
                @Html.TextBoxFor(m => m.Yil, new { @class = "validate" })
                <label for="Yil">Yıl</label>
            </div>
            <div class="input-field col s6">
                @Html.TextBoxFor(m => m.Renk, new { @class = "validate" })
                <label for="Renk">Renk</label>
            </div>
            @Html.TextBoxFor(m => m.Py_ID, new { @class = "validate" })
        </div>
                <div class="row">
                    <div class="input-field col s6">
                        <i class="material-icons prefix">account_circle</i>
                        @Html.TextBoxFor(m => m.Giris_Tarihi, new { @class = "validate" })
                        <label for="Giris_Tarihi">Giriş Tarihi</label>
                    </div>
                    
                </div>
                <div class="col center m12 s12">
                    <button class="waves-effect waves-light btn btn-small red lighten-2"><i class="material-icons left">chevron_right</i><i class="material-icons right">chevron_left</i>Güncelle</button>
                </div>
            }

        </div>
    </div>
</div>

otopark_otomasyonu/Views/Arac/AracGoster.cshtml
@{
    ViewBag.Title = "AracGoster";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="section">

        <div class="row">
            <div class="col s12 center">
                <h3><i class="mdi-content-send brown-text"></i></h3>
                <h4>KİŞİ ARACI KAYIT</h4>
                <p class="center light">Kişilerin Araçlarını Kayıt Edebildikleri Alan</p>
                <hr class="hr">
                <div class="row">
                    <form class="col s12" method="post">
                        <div class="row">
                            <div class="input-field col s6">
                                <input name="Kisi_ID" type="number" class="validate">
                                <label for="Kisi_ID">Araç Kime Ait - ID</label>
                            </div>
                            <div class="input-field col s6">
                                <i class="material-icons prefix">account_circle</i>
                                <input placeholder="Plaka" name="Plaka" type="text" class="validate">
                                <label for="Plaka" class="active">Araç Bilgileriniz</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6">
                                <input name="Marka_ID" type="text" class="validate">
                                <label for="Marka_ID">Markası</label>
                            </div>
                            <div class="input-field col s6">
                                <i class="material-icons prefix">people_outline</i>
                                <input name="Renk" type="text" class="validate">
                                <label for="Renk">Rengi</label>
                            </div>
                        </div>
                        <div class="col m12 s12">
                            <button type="submit" class="waves-effect waves-light btn btn-small red lighten-2"><i class="material-icons left">chevron_right</i><i class="material-icons right">chevron_left</i>Aracınızı Kayıt Edin !</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
<!--================End Services_area =================-->
<!-- Section 1 Bitiş-->